// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNP9D_FQzf_twkw1XC98TqI60x1tCdshY',
    appId: '1:787379552894:web:64eed4a0c26ca569f74e2f',
    messagingSenderId: '787379552894',
    projectId: 'travelagent-9bcb4',
    authDomain: 'travelagent-9bcb4.firebaseapp.com',
    storageBucket: 'travelagent-9bcb4.appspot.com',
    measurementId: 'G-V1X7R144TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCFpb30Lv8oQ-RMtfueOen7-INvjgFczs',
    appId: '1:787379552894:android:3c104d40b61967aff74e2f',
    messagingSenderId: '787379552894',
    projectId: 'travelagent-9bcb4',
    storageBucket: 'travelagent-9bcb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjzDbpNYlV3cbLgfbTavBcx0RdgmiaKsw',
    appId: '1:787379552894:ios:1028443354297bfcf74e2f',
    messagingSenderId: '787379552894',
    projectId: 'travelagent-9bcb4',
    storageBucket: 'travelagent-9bcb4.appspot.com',
    iosClientId: '787379552894-v80cec96bua1pqori82aij4akb57a9ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelagent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjzDbpNYlV3cbLgfbTavBcx0RdgmiaKsw',
    appId: '1:787379552894:ios:1028443354297bfcf74e2f',
    messagingSenderId: '787379552894',
    projectId: 'travelagent-9bcb4',
    storageBucket: 'travelagent-9bcb4.appspot.com',
    iosClientId: '787379552894-v80cec96bua1pqori82aij4akb57a9ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelagent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNP9D_FQzf_twkw1XC98TqI60x1tCdshY',
    appId: '1:787379552894:web:83b7357359c06ee1f74e2f',
    messagingSenderId: '787379552894',
    projectId: 'travelagent-9bcb4',
    authDomain: 'travelagent-9bcb4.firebaseapp.com',
    storageBucket: 'travelagent-9bcb4.appspot.com',
    measurementId: 'G-3GB768X938',
  );
}